version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

  nestjs:
    container_name: nestjs
    build: nestjs
    environment:
      ENV: local
    volumes:
      - /nestjs/app:/src/app
      - :/src/app/node_modules
    ports:
      - "3001:3000"

  nextjs:
    container_name: nextjs
    build: nextjs
    environment:
      - ENV=local
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /nextjs/app:/app
      - /app/node_modules
    ports:
      - "3002:3000"